# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabComment < Formula
  desc "CLI to create and hide GitLab comments
"
  homepage "https://github.com/yuyaban/gitlab-comment"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yuyaban/gitlab-comment/releases/download/v0.1.5/gitlab-comment_0.1.5_darwin_arm64.tar.gz"
      sha256 "65eb761c3e1924ab8fca7b7708e89d0d287bf10133c45dae8faa141d92695681"

      def install
        bin.install "gitlab-comment"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuyaban/gitlab-comment/releases/download/v0.1.5/gitlab-comment_0.1.5_darwin_amd64.tar.gz"
      sha256 "8183158baddb191c409a9eadd7a3b2ab0c0071c3b49b98dd70ce270d226805dc"

      def install
        bin.install "gitlab-comment"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yuyaban/gitlab-comment/releases/download/v0.1.5/gitlab-comment_0.1.5_linux_amd64.tar.gz"
      sha256 "66487f3bfd5e1c6c83b1cb7eff1bc75b6fbaba453a339675a91683e34cb1224f"

      def install
        bin.install "gitlab-comment"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuyaban/gitlab-comment/releases/download/v0.1.5/gitlab-comment_0.1.5_linux_arm64.tar.gz"
      sha256 "21dc453c0b69966a9c81ba851516a6a76513e78345e81ea25f58bb37d69e94b2"

      def install
        bin.install "gitlab-comment"
      end
    end
  end

  test do
    system "#{bin}/gitlab-comment --version"
  end
end
